/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;
import controle.ControleUsuarios;
import java.util.Arrays;
import modelo.Usuario;

/**
 *
 * @author Lucas
 */
public class LoginJPanel extends javax.swing.JPanel {

    
    private ControleUsuarios listaUsuarios;
    private MenuPrincipalJPanel menuPrincipal;
    private MainJFrame principalJFrame;
    /**
     * Creates new form LoginJPanel
     */
    public LoginJPanel(ControleUsuarios novaListaUsuarios, MainJFrame principalJFrame) {
        
        initComponents();
        
        this.listaUsuarios = novaListaUsuarios;
        this.principalJFrame = principalJFrame;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LoginjLabel = new javax.swing.JLabel();
        loginNomejLabel = new javax.swing.JLabel();
        loginNomejTextField = new javax.swing.JTextField();
        loginSenhajLabel = new javax.swing.JLabel();
        loginSenhajPasswordField = new javax.swing.JPasswordField();
        loginCadastrarjButton = new javax.swing.JButton();
        loginEntrarjButton = new javax.swing.JButton();

        LoginjLabel.setBackground(new java.awt.Color(153, 153, 153));
        LoginjLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LoginjLabel.setText("Login");

        loginNomejLabel.setText("Nome");

        loginSenhajLabel.setText("Senha");

        loginCadastrarjButton.setText("Cadastrar");
        loginCadastrarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginCadastrarjButtonActionPerformed(evt);
            }
        });

        loginEntrarjButton.setText("Entrar");
        loginEntrarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginEntrarjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginSenhajLabel)
                            .addComponent(loginNomejLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loginSenhajPasswordField)
                            .addComponent(loginNomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(LoginjLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(loginCadastrarjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginEntrarjButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LoginjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(loginNomejLabel)
                    .addComponent(loginNomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(loginSenhajPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginSenhajLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginEntrarjButton)
                    .addComponent(loginCadastrarjButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginCadastrarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginCadastrarjButtonActionPerformed
        String loginNome = loginNomejTextField.getText();
        char[] loginSenha = loginSenhajPasswordField.getPassword();
        
        if(!loginNome.isEmpty() && !Arrays.toString(loginSenha).isEmpty())
        {
            
            if(!listaUsuarios.checarUsuarioCadastrado(loginNome))
            {
                Usuario user = new Usuario();
                user.setNome(loginNomejTextField.getText());
                user.setSenha(loginSenhajPasswordField.getPassword());
                
                listaUsuarios.addUsuario(user);
                
            }
            else
                System.out.print("Usuario já cadastrado no sistema");
            
            loginNomejTextField.setText("");
            loginSenhajPasswordField.setText(null);
           
        }
    }//GEN-LAST:event_loginCadastrarjButtonActionPerformed

    private void loginEntrarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginEntrarjButtonActionPerformed
        String loginNome = loginNomejTextField.getText();
        char[] loginSenha = loginSenhajPasswordField.getPassword();
        
        if(!loginNome.isEmpty() && !Arrays.toString(loginSenha).isEmpty())
        {
            
            if(listaUsuarios.checarUsuarioCadastrado(loginNome))
            {
                Usuario user = listaUsuarios.loginUsuario(loginNome, loginSenha);
                if(user != null)
                {
                    if(menuPrincipal == null)
                        menuPrincipal = new MenuPrincipalJPanel(this, user, listaUsuarios, principalJFrame);
                    
                    menuPrincipal.setSize(this.getSize());

                    //JRootPane rootPane = this.getRootPane();

                    this.setVisible(false);
                    principalJFrame.setContentPane(menuPrincipal);

                    menuPrincipal.setVisible(true);
                }
                else
                    System.out.print("Senha incorreta");
                 
            }
            else
                System.out.print("Usuario não cadastrado");
            
            loginNomejTextField.setText(null);
            loginSenhajPasswordField.setText(null);
           
        } 
        
    }//GEN-LAST:event_loginEntrarjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoginjLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginCadastrarjButton;
    private javax.swing.JButton loginEntrarjButton;
    private javax.swing.JLabel loginNomejLabel;
    private javax.swing.JTextField loginNomejTextField;
    private javax.swing.JLabel loginSenhajLabel;
    private javax.swing.JPasswordField loginSenhajPasswordField;
    // End of variables declaration//GEN-END:variables



}
