package visao;
import controle.ControleQuartos;
import modelo.*;
import controle.ControleUsuarios;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import javax.swing.JPanel;

/**
 *
 * @author Lucas
 */
public class MenuPrincipalJPanel extends javax.swing.JPanel {

    private ControleUsuarios listaUsuarios;
    private Usuario usuario;
    private JPanel telaAnterior;
    private MenuQuartoJPanel menuQuarto;
    private ControleQuartos listaQuartos;
    private MainJFrame principalJFrame;
    //private ComboBoxModel comboBoxListaQuartosNumeros;
    
    public MenuPrincipalJPanel(){
         initComponents();
    }
    
    public MenuPrincipalJPanel(JPanel telaAnterior,Usuario usuario, ControleUsuarios listaUsuarios, MainJFrame mainFrame) {
        listaQuartos = new ControleQuartos();
        addQuartos();
        
        initComponents();

        this.telaAnterior = telaAnterior;
        this.usuario = usuario;
        this.listaUsuarios = listaUsuarios;
        setSessao(usuario);
        
        principalJFrame = mainFrame;
        
        
        
        
    }
    
    public void setUsuarioSessao(Usuario novoUsuario){
        this.usuario = novoUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cabecalhoMenuPrincipaljTextField = new javax.swing.JTextField();
        sairProgramajButton = new javax.swing.JButton();
        editarContajButton = new javax.swing.JButton();
        numeroQuartojLabel = new javax.swing.JLabel();
        quartoNumeroEntrarjButton = new javax.swing.JButton();
        quartoNumerojComboBox = listaQuartos.getJComboBoxNumerosDeQuartos();

        sairProgramajButton.setText("Sair");
        sairProgramajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairProgramajButtonActionPerformed(evt);
            }
        });

        editarContajButton.setText("Editar Conta");
        editarContajButton.setEnabled(false);

        numeroQuartojLabel.setText("Quarto");

        quartoNumeroEntrarjButton.setText("Entrar");
        quartoNumeroEntrarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quartoNumeroEntrarjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(cabecalhoMenuPrincipaljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editarContajButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sairProgramajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(numeroQuartojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quartoNumerojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quartoNumeroEntrarjButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sairProgramajButton)
                    .addComponent(editarContajButton)
                    .addComponent(cabecalhoMenuPrincipaljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroQuartojLabel)
                    .addComponent(quartoNumeroEntrarjButton)
                    .addComponent(quartoNumerojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(213, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sairProgramajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairProgramajButtonActionPerformed
        
        this.setVisible(false);
        principalJFrame.setContentPane(telaAnterior);
        telaAnterior.setVisible(true);
        
    }//GEN-LAST:event_sairProgramajButtonActionPerformed

    private void quartoNumeroEntrarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quartoNumeroEntrarjButtonActionPerformed
        
        Quarto quartoSelecionado = listaQuartos.getQuartoByNumber(quartoNumerojComboBox.getSelectedIndex());
        menuQuarto = new MenuQuartoJPanel(this, quartoSelecionado, principalJFrame);
        
        this.setVisible(false);
        principalJFrame.setContentPane(menuQuarto);
        menuQuarto.setVisible(true);
        
    }//GEN-LAST:event_quartoNumeroEntrarjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cabecalhoMenuPrincipaljTextField;
    private javax.swing.JButton editarContajButton;
    private javax.swing.JLabel numeroQuartojLabel;
    private javax.swing.JButton quartoNumeroEntrarjButton;
    private javax.swing.JComboBox quartoNumerojComboBox;
    private javax.swing.JButton sairProgramajButton;
    // End of variables declaration//GEN-END:variables

    private void setSessao(Usuario user) {
        OffsetDateTime a = null;
        cabecalhoMenuPrincipaljTextField.setEnabled(false);
        cabecalhoMenuPrincipaljTextField.setEditable(false);
        
        
        
        if(user.getDataUltimaVisita() != null)
            cabecalhoMenuPrincipaljTextField.setText(user.getNome() + " Ultima visita em: " + user.getDataUltimaVisita().format(DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT)) );
        else
            cabecalhoMenuPrincipaljTextField.setText(user.getNome() + " - " + "Esta é sua primeira visita! :D" );
        user.setDataUltimaVisita( LocalDateTime.now());
    }

    private void addQuartos() {
        
        //new DefaultComboBoxModel(listaQuartos.getArrayQuartosNumero())
        for(int i = 1; i < 7; i++)
            listaQuartos.criarQuarto(i);
    }
}
