/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import modelo.Quarto;
import modelo.Produto;

/**
 *
 * @author Lucas
 */
public class MenuQuartoJPanel extends javax.swing.JPanel {

    private Quarto quarto;
    private MenuCarrinhoJPanel carrinhoJPanel;
    private JPanel telaAnterior;
    private DefaultTableModel modeloTabelaProdutosPagos;
    private DefaultTableModel modeloTabelaProdutosAPagar;
    private MainJFrame principalJFrame;
    /**
     * Creates new form QuartoMenu
     * @param telaAnterior
     * @param quartoSelecionado
     */
    public MenuQuartoJPanel(JPanel telaAnterior, Quarto quartoSelecionado, MainJFrame mainFrame) {
        
        initComponents();
        
        this.telaAnterior = telaAnterior;
        quarto = quartoSelecionado;
        setCabecalho();
        setListasDeProdutos();
        pagarProdutojButton.setEnabled(false);
        principalJFrame = mainFrame;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cabecalhoQuartojTextField = new javax.swing.JTextField();
        voltarTelajButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pagarProdutojButton = new javax.swing.JButton();
        adicionarProdutojButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaProdutosPagos = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelaProdutosAPagar = new javax.swing.JTable();

        cabecalhoQuartojTextField.setEnabled(false);

        voltarTelajButton.setText("Voltar");
        voltarTelajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarTelajButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Produtos Pagos");

        jLabel2.setText("Produtos A pagar");

        pagarProdutojButton.setText("Pagar");
        pagarProdutojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarProdutojButtonActionPerformed(evt);
            }
        });

        adicionarProdutojButton.setText("Adicionar Produto");
        adicionarProdutojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarProdutojButtonActionPerformed(evt);
            }
        });

        tabelaProdutosPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data Pagamento", "Nome", "Preco"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaProdutosPagos.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tabelaProdutosPagos);
        if (tabelaProdutosPagos.getColumnModel().getColumnCount() > 0) {
            tabelaProdutosPagos.getColumnModel().getColumn(0).setResizable(false);
            tabelaProdutosPagos.getColumnModel().getColumn(1).setResizable(false);
            tabelaProdutosPagos.getColumnModel().getColumn(2).setResizable(false);
        }

        tabelaProdutosAPagar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data Criacao", "Nome", "Preco"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaProdutosAPagar.getTableHeader().setReorderingAllowed(false);
        tabelaProdutosAPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutosAPagarMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tabelaProdutosAPagar);
        if (tabelaProdutosAPagar.getColumnModel().getColumnCount() > 0) {
            tabelaProdutosAPagar.getColumnModel().getColumn(0).setResizable(false);
            tabelaProdutosAPagar.getColumnModel().getColumn(1).setResizable(false);
            tabelaProdutosAPagar.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adicionarProdutojButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pagarProdutojButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cabecalhoQuartojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(voltarTelajButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 197, Short.MAX_VALUE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cabecalhoQuartojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltarTelajButton))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pagarProdutojButton)
                    .addComponent(adicionarProdutojButton))
                .addGap(102, 107, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarProdutojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarProdutojButtonActionPerformed
        carrinhoJPanel = new MenuCarrinhoJPanel(this, principalJFrame);
        
        this.setVisible(false);
        principalJFrame.setContentPane(carrinhoJPanel);
        carrinhoJPanel.setVisible(true);
        
        
    }//GEN-LAST:event_adicionarProdutojButtonActionPerformed

    private void voltarTelajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarTelajButtonActionPerformed
        this.setVisible(false);
        principalJFrame.setContentPane(telaAnterior);
        telaAnterior.setVisible(true);
    }//GEN-LAST:event_voltarTelajButtonActionPerformed

    private void pagarProdutojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarProdutojButtonActionPerformed
        
        String nomeProduto =(String) modeloTabelaProdutosAPagar.getValueAt(tabelaProdutosAPagar.getSelectedRow(),1);

        Produto produtoApagar = quarto.getProdutoAderidoPorNome(nomeProduto);
        
        //System.out.println("TRETA" + produtoApagar.getNome());
        quarto.pagarProduto(produtoApagar);
        modeloTabelaProdutosAPagar.removeRow(tabelaProdutosAPagar.getSelectedRow());
        modeloTabelaProdutosPagos.addRow(produtoApagar.getArrayStringDeDadosComDataPagamento());
        
        pagarProdutojButton.setEnabled(false);
        
    }//GEN-LAST:event_pagarProdutojButtonActionPerformed

    private void tabelaProdutosAPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutosAPagarMouseClicked
        int produtoSelecionado = tabelaProdutosAPagar.getSelectedRow();
        
        if(produtoSelecionado >= 0 && produtoSelecionado <= tabelaProdutosAPagar.getRowCount()){
            pagarProdutojButton.setEnabled(true);
        }
        else
           System.out.println("Produto nao encontrado");
    }//GEN-LAST:event_tabelaProdutosAPagarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarProdutojButton;
    private javax.swing.JTextField cabecalhoQuartojTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton pagarProdutojButton;
    private javax.swing.JTable tabelaProdutosAPagar;
    private javax.swing.JTable tabelaProdutosPagos;
    private javax.swing.JButton voltarTelajButton;
    // End of variables declaration//GEN-END:variables

    private void setCabecalho() {
        cabecalhoQuartojTextField.setText(String.valueOf(quarto.getNumero()));
        cabecalhoQuartojTextField.setEditable(false);
        cabecalhoQuartojTextField.setEnabled(false);
    }

    private void setListasDeProdutos() {
        
        modeloTabelaProdutosAPagar = (DefaultTableModel) this.tabelaProdutosAPagar.getModel();
        modeloTabelaProdutosPagos = (DefaultTableModel) this.tabelaProdutosPagos.getModel();
       
        if( quarto.listaProdutosAderidos != null)
        {
            for (Produto produto : quarto.listaProdutosAderidos) {
                this.modeloTabelaProdutosAPagar.addRow(produto.getArrayStringDeDadosComDataAdesao());
            }
        }
        
        if( quarto.listaProdutosPagos != null)
        {
            for (Produto produto : quarto.listaProdutosPagos) {
                this.modeloTabelaProdutosPagos.addRow(produto.getArrayStringDeDadosComDataPagamento());
            }
        }      
    }
   public void adicionarCarrinho(ArrayList<Produto> listaDeProdutosDoCarrinho){      
            for (Produto produto : listaDeProdutosDoCarrinho) {
            quarto.addProdutoAoQuarto(produto);
            modeloTabelaProdutosAPagar.addRow(produto.getArrayStringDeDadosComDataAdesao());
        }
   }
}
